---
title: "Snake Draft Assistant"
output: html_document
---

This application recommends selections by position based on how much value they add to your team compared to the players likely to be available the next to time you select.

It does this by analyzing:

1. Predicted points per game of every player
2. Your roster
3. Average draft position

[Jump to the app here](http://ec2-54-213-112-234.us-west-2.compute.amazonaws.com:3838/stats-corner/2016/snake-assistant/) or read the analytical details below.

### Predicted Points Per Game
Many websites produce preseason forecasts of player PPG. The site [FantasyFootballAnalytics](http://fantasyfootballanalytics.net/) aggregates those predictions and produces a weighted average that [proves to be more accurate](http://fantasyfootballanalytics.net/2017/03/best-fantasy-football-projections-2017.html) than any once source.

I am a subscriber to the site and downloaded their data for use in the app.

### Your Roster
Roster analysis consists of three components: 

1. Roster settings
2. Your current roster
3. BYE weeks of your current roster

##### Roster Settings
Before you draft input the position limits of your starting lineup. 

For example: 1 QB, 2 RBs, 2 WRs, 1 TE, 1 FLEX, 1 DST and 1 K. 

The app can handle leagues with either FLEX (RB/WR/TE) or OP (QB/RB/WR/TE) positions. 

##### Your current roster 
As you draft players and enter them into the app a weekly starting lineup is assembled based on roster limits and the expected number of points scored each week is calculated. If your starting lineup for a certain position has met its limit then a player will be considered for FLEX/OP. But if they aren't good enough to crack your starting lineup at any position then they add 0 points to your roster no matter what their projected PPG are.

##### Taking BYE weeks into account
When a player has a BYE, of course they don't play. When your team amasses multiple BYEs in a given week, you'll be stretched thin and likely lose. These recommendations take BYE weeks into account and will elevate players who do not have overlapping BYEs with players at the same position. 

### Average Draft Position
To make recomendations the app compares the Value Added by each player not against everyone other available player, but against the players most likely to remain in the draft pool the next time you pick (based on yourorder in the draft sequence). 

For example, let's say you have the first pick in a 10 team league.

Antonio Brown is recommended to be the top pick not because his projected PPG (17.3) is that much greater than Julio Jones (#2 WR, 15.4 PPG), but because the next time you draft the best available WR is likely to be Alshon Jeffrey whose predicted 12.3 PPG is a 5 point dropoff, far greater than the dropoff at any other position.

### Check It Out!

[You can check out the app here](http://ec2-54-213-112-234.us-west-2.compute.amazonaws.com:3838/stats-corner/2016/snake-assistant/) or [access the code here](github.com/johnckane/stats_corner/2016/snake_assistant).

Feedback? contact me at statscorner[at]gmail[dot]com. 

###### Document History
###### Intially Published: April 26, 2017
